import mongoose, { Schema, Document, Types } from 'mongoose';

// 1. Interface for the individual item sub-documents
export interface ICartItem {
  _id?: Types.ObjectId; // Automatically generated by Mongoose
  itemId: Types.ObjectId;
  quantity: number;
  rentalDays: number;
  startDate: string;
  endDate: string;
}

// 2. Interface for the Main Cart Document (extends mongoose Document)
export interface ICart extends Document {
  userId: Types.ObjectId;
  items: ICartItem[];
  createdAt: Date;
  updatedAt: Date;
}

const CartSchema = new Schema<ICart>({
  userId: {
    type: Schema.Types.ObjectId,
    required: true,
    ref: 'User'
  },
  items: [
    {
      itemId: {
        type: Schema.Types.ObjectId,
        required: true,
        ref: 'Item'
      },
      quantity: {
        type: Number,
        default: 1,
        min: 1
      },
      rentalDays: {
        type: Number,
        default: 1,
        min: 1
      },
      startDate: { type: String, required: true },
      endDate: { type: String, required: true },
    }
  ]
}, {
  timestamps: true
});

// 3. Export the model with the applied Interface type
const Cart = mongoose.model<ICart>('Cart', CartSchema);
export default Cart;